### ISSUE TITLE
CoL widget bug: search for higher taxa do not work

### ISSUE THREAD

**Issue by MortenHofft** [gbif/hp-legume#8]
It isn't possible to change the higher taxon filter from Fabaceae in search
https://hp-legume.gbif-staging.org/taxonomy/search?TAXON_ID=27388-1&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=50&offset=0

No matter what one does it will return the same results and a refresh will reset the filter to `Fabaceae`

The relevant issue in CoL is https://github.com/CatalogueOfLife/portal-components/issues/18

Once this issue is fixed, then it will be necessary to update the version of the CoL library used. I've added this as an option in [the config](https://github.com/gbif/hp-legume/blob/master/_config.yml#L78)

**Comment by CaroleSinou** [comment]
@MortenHofft is it also why, when on a taxon page, when we click on the number of species or subspecies, it brings back to the entire Fabaceae list and not the specific taxon?

*Example*:
https://hp-legume.gbif-staging.org/taxonomy/taxon/21580-1

If we click on "2" for the subspecies, it brings back to :
https://hp-legume.gbif-staging.org/taxonomy/search?TAXON_ID=21580-1&rank=subspecies&status=accepted&status=provisionally%20accepted

Instead of:
https://hp-legume.gbif-staging.org/taxonomy/search?TAXON_ID=x4VX&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=50&offset=0&q=adenolobus&rank=subspecies&status=accepted&status=provisionally%20accepted

**Comment by MortenHofft** [comment]
Sounds like it is the same issue yes

**Comment by thomasstjerne** [comment]
This should be fixed in https://github.com/CatalogueOfLife/portal-components/releases/tag/v0.7.11
